# Generated by Django 4.0.2 on 2023-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='api_key',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='secret',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
